### ISSUE TITLE
How to build PDF Sharp with Strong name?

### ISSUE THREAD

**Issue by SeanBerrir** [empira/PDFsharp#104]
Hi Team,

Need to install PDFSharp to Global Assembly Cache. However, it doesn't have a strong name. Building it with a strong name for each of the projects is throwing errors.   Though build succeeded when building the entire solution as is.  But won't install in GAC. 

Any  thoughts?

**Comment by StLange** [comment]
Very good point! During development of PDFsharp 6.0 we removed all strong names because there is no GAC anymore. When we retrofit PDFsharp 6.1 for .NET Framework / Standard 2.0 we forgot that. With the very soon coming Preview 3 of PDFsharp 6.1 all assemblies in the NuGet packages are again signed with a strong name.
Thank you for reminding us.

**Comment by SeanBerrir** [comment]
Thank you. Glad to help.

**Comment by StLange** [comment]
Done in 6.1.0 Preview 3
