### ISSUE TITLE
Infinite Loop in ‎TopDownFormatter::FormatOnAreas

### ISSUE THREAD

**Issue by mnadeem-mercedes-hpp** [empira/PDFsharp#185]
The loop in ‎TopDownFormatter::FormatOnAreas has the tendency to become an infinite loop in some cases.

This deadly loop caused our web farm to go down and cause great inconvenience. 

## Steps to Reproduce the Behavior

Please run the MigraDoc solution
[Issue.zip](https://github.com/user-attachments/files/17363086/Issue.zip)

It would be nice to have a cancellation token in methods with dynamic loops - A cancellation token in this method would have allowed me to detect and stop the infinite loop to save the application on runtime.

I have stopped using this plugin in the application I am currently working on, however I would like to use it again in the future once it gets stable.

**Comment by ThomasHoevel** [comment]
We fixed that infinite loop in the current internal build and fix will be included in the next Preview release.

We will not add a cancellation token in the foreseeable future.

Cause of the problem was a single paragraph with three large images that was too large to fit a single page. While this should not cause an infinite loop, it still is an unusual situation and thus the bug remained unfound for such a long time.

**Comment by ThomasHoevel** [comment]
Issue should be resolved with PDFsharp 6.2.0 Preview 2.
