### ISSUE TITLE
Dependency on PowerShell 7.* prevent building on Windows 10

### ISSUE THREAD

**Issue by PaulStSmith** [empira/PDFsharp#52]
I just cloned the repository, and following the `readme.md` I tried to run the `.\dev\download-assets.ps1` on my dev-box: VS2022 running on Windows 10.

This was the result:

![image](https://github.com/empira/PDFsharp/assets/118175402/b9d682d4-f975-4db9-ac80-a19ae5c03398)

This dependency on PowerShell prevents developers running Windows 10 from building the master branch of PDFsharp.

**Comment by cjberg** [comment]
There are two different editions of PowerShell: the original Windows PowerShell (latest and final version is 5.1) and the modern Microsoft PowerShell a.k.a. PowerShell Core (currently v7.3.9). The latter can also be installed on Mac and Linux.

You can install both on Windows, as they can co-exist. It's recommended by Microsoft and the PowerShell community.

The `winget upgrade` command report failure simply because you haven't installed it, as the `Microsoft.PowerShell` id belongs to the newer edition. Run `winget install --exact --id Microsoft.PowerShell --source winget` to install ([documentation](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#winget)).
